export const INPUT_1 = [
    { addr: "X0", input: "START PB 1" },
    { addr: "X1", input: "START PB 2" },
    { addr: "X2", input: "RESET PB" },
    { addr: "X3", input: "EMG PB" },
    { addr: "X4", input: "DIGITAL PRESSURE SW" },
    { addr: "X5", input: "REJECTION BIN SENSOR-1" },
    { addr: "X6", input: "LIGHT CURTAIN-1" },
    { addr: "X7", input: "INDEXER HOME POSITION SENSOR" },
    { addr: "X10", input: "INDEXER SERVO ERROR" },
    { addr: "X11", input: "ST1-PART PRESENT SENSOR" },
    { addr: "X12", input: "ST2-PROBE CYL1 FWD RD" },
    { addr: "X13", input: "ST2-PROBE CYL1 RET RD" },
    { addr: "X14", input: "ST2-PROBE CYL2 FWD RD" },
    { addr: "X15", input: "ST2-PROBE CYL2 RET RD" },
    { addr: "X16", input: "ST2-RESISTANCE OK" },
    { addr: "X17", input: "ST2-RESISTANCE NOK" },
    { addr: "X20", input: "ST3-PROBE CYL1 FWD RD" },
    { addr: "X21", input: "ST3-PROBE CYL1 RET RD" },
   
  ];
  
  export const INPUT_2 =[
    { addr: "X22", input: "ST3-PROBE CYL2 FWD RD" },
    { addr: "X23", input: "ST3-PROBE CYL2 RET RD" },
    { addr: "X24", input: "ST3-IMPEDANCE OK" },
    { addr: "X25", input: "ST3-IMPEDANCE NOK" },
    { addr: "X26", input: "ST4-CB1 CLAMP CYL FWD RD" },
    { addr: "X27", input: "ST4-CB1 CLAMP CYL RET RD" },
    { addr: "X30", input: "ST4-CB1 PRESS SERVO HOME POSITION LS" },
    { addr: "X31", input: "ST4-CB1 PRESS SERVO FWD POSITION LS" },
    { addr: "X32", input: "ST4-CB1 PRESS SERVO RET POSITION LS" },
    { addr: "X33", input: "ST4-CB1 PRESS SERVO ERROR" },
    { addr: "X34", input: "ST5-CB2 CLAMP CYL FWD RD" },
    { addr: "X35", input: "ST5-CB2 CLAMP CYL RET RD" },
    { addr: "X36", input: "ST5-CB2 PRESS SERVO HOME POSITION LS" },
    { addr: "X37", input: "ST5-CB2 PRESS SERVO FWD POSITION LS" },
    { addr: "X40", input: "ST5-CB2 PRESS SERVO RET POSITION LS" },
    { addr: "X41", input: "ST5-CB2 PRESS SERVO ERROR" },
    { addr: "X42", input: "ST5-CAMERA OK" },
    { addr: "X43", input: "ST5-CAMERA NOK" },
  
  ]
  
  export const INPUT_3 =[
    { addr: "X44", input: "ST-5 CAMERA READY" },
    { addr: "X45", input: "ST6-CAMERA OK" },
    { addr: "X46", input: "ST6-CAMERA NOK" },
    { addr: "X47", input: "ST-6 CAMERA READY" },
    { addr: "X50", input: "ST-6 BEARING CHECK CYL FWD RD" },
    { addr: "X51", input: "ST-6 BEARING CHECK CYL RET RD" },
    { addr: "X52", input: "ST6-BEARING ANGLE OK" },
    { addr: "X53", input: "ST6-BEARING ANGLE NOK LOW" },
    { addr: "X54", input: "ST6-BEARING ANGLE NOK HIGH" },
    { addr: "X55", input: "ST7-LASER MARKING M/C READY" },
    { addr: "X56", input: "ST7-LASER MARKING M/C DEFAULT" },
    { addr: "X57", input: "ST8-PICK & PLACE UP/DN CYL FWD RD" },
    { addr: "X60", input: "ST8-PICK & PLACE UP/DN CYL RET RD" },
    { addr: "X61", input: "ST8-GRIPPER CYL FWD RD" },
    { addr: "X62", input: "ST8-GRIPPER CYL RET RD" },
    { addr: "X63", input: "ST8-PICK & PLACE SERVO HOME POSITION LS" },
    { addr: "X64", input: "ST8-PICK & PLACE SERVO FWD POSITION LS" },
    { addr: "X65", input: "ST8-PICK & PLACE SERVO RET POSITION LS" },
  
  ]
  
  export const INPUT_4 =[
    { addr: "X66", input: "ST8-PICK & PLACE SERVO ERROR" },
    { addr: "X67", input: "SPARE" },
    { addr: "X70", input: "DOOR LIMIT SW-1" },
    { addr: "X71", input: "DOOR LIMIT SW-2" },
    { addr: "X72", input: "DOOR LIMIT SW-3" },
    { addr: "X73", input: "DOOR LIMIT SW-4" },
    { addr: "X74", input: "DOOR LIMIT SW-5" },
    { addr: "X75", input: "DOOR LIMIT SW-6" },
    { addr: "X76", input: "SCANNER READING OK" },
    { addr: "X77", input: "SCANNER READING ERROR" },
    { addr: "X100", input: "ST4-CB1 LOAD CELL CYL FWD RD" },
    { addr: "X101", input: "ST4-CB1 LOAD CELL CYL RET RD" },
    { addr: "X102", input: "ST5-CB2 LOAD CELL CYL FWD RD" },
    { addr: "X103", input: "ST5-CB2 LOAD CELL CYL RET RD" },
    { addr: "X104", input: "SPARE" },
    { addr: "X105", input: "ANTI PINCH SENSOR" },
    { addr: "X106", input: "SPARE" },
    { addr: "X107", input: "SPARE" }
  ]
  